/**
 * DO NOT EDIT -- this file is auto-generated by scripts/generate_worker_recipes.py
 * from recipes/*.toml. To update, run: python scripts/generate_worker_recipes.py
 */

/** A rottengenizdat recipe definition. */
export interface Recipe {
  slug: string;
  name: string;
  mode: "sequential" | "branch";
  steps: number;
  effects: string;
}

/** All available recipes. */
export const RECIPES: readonly Recipe[] = [
  { slug: "barely-there", name: "barely-there", mode: "branch", steps: 2, effects: "dry(w=0.9) + rave(vintage t=0.7 w=0.1 d=0,1)" },
  { slug: "bitcrushed-god", name: "bitcrushed-god", mode: "sequential", steps: 2, effects: "rave(percussion t=1.5 q=1.0) -> rave(sol_full t=0.8 q=0.5)" },
  { slug: "bone-xray", name: "bone-xray", mode: "branch", steps: 3, effects: "rave(percussion t=1.2) + rave(vintage t=0.9) + rave(musicnet t=1.0)" },
  { slug: "choir-of-ghosts", name: "choir-of-ghosts", mode: "branch", steps: 3, effects: "recipe(w=0.4) + recipe(w=0.35) + recipe(w=0.25)" },
  { slug: "choir-practice", name: "choir-practice", mode: "branch", steps: 5, effects: "rave(VCTK t=0.7 n=0.1) + rave(VCTK t=1.0 n=0.15) + rave(VCTK t=1.3 n=0.2) + rave(VCTK t=1.6 n=0.25 d=4,5,6,7,8,9,10,11) + rave(isis t=0.9 n=0.15 d=0,1,2,3,4,5)" },
  { slug: "congregation", name: "congregation", mode: "branch", steps: 7, effects: "rave(VCTK t=1.2 n=0.15 d=0,1,2,3) + rave(VCTK t=0.8 n=0.3 d=4,5,6,7) + rave(VCTK t=1.5 n=0.2 d=8,9,10,11) + rave(isis t=1.0 n=0.1 d=0,1,2,3,4,5,6,7) + rave(isis t=1.3 n=0.2 d=8,9,10,11,12,13,14,15) + rave(sol_ordinario t=0.9 d=0,2,4,6,8,10) + rave(sol_full t=1.1 d=1,3,5,7,9,11)" },
  { slug: "drunk-choir", name: "drunk-choir", mode: "branch", steps: 3, effects: "rave(VCTK t=1.4 n=0.2) + rave(VCTK t=0.8 n=0.4 d=4,5,6,7,8) + rave(isis t=1.1 n=0.15)" },
  { slug: "fever-dream", name: "fever-dream", mode: "sequential", steps: 3, effects: "rave(nasa t=2.5 n=0.8 rev) -> rave(percussion t=2.0 n=0.5 shuf=3 q=0.8) -> rave(VCTK t=1.8 shuf=2)" },
  { slug: "ghost-in-the-machine", name: "ghost-in-the-machine", mode: "sequential", steps: 2, effects: "rave(vintage t=0.7 d=0,1,2,3) -> rave(VCTK t=0.5 d=0,1 mix=0.3)" },
  { slug: "hall-of-mirrors", name: "hall-of-mirrors", mode: "sequential", steps: 3, effects: "rave(vintage t=0.9 d=0,1,2,3,4,5) -> rave(vintage t=1.0) -> rave(vintage t=1.1)" },
  { slug: "haunted-dub", name: "haunted-dub", mode: "branch", steps: 2, effects: "dry(w=0.05) + rave(vintage t=1.3 n=0.15 w=0.3 d=0,1,2,3,4,5)" },
  { slug: "nature-documentary", name: "nature-documentary", mode: "branch", steps: 3, effects: "rave(nasa t=1.3 n=0.1) + rave(sol_ordinario t=0.8) + rave(sol_full t=1.0 d=0,2,4,6,8,10)" },
  { slug: "needle-drop", name: "needle-drop", mode: "sequential", steps: 1, effects: "rave(vintage t=0.6 d=0,1 mix=0.4)" },
  { slug: "organ-donor", name: "organ-donor", mode: "branch", steps: 3, effects: "dry(w=0.5) + rave(sol_ordinario t=0.9 w=0.3) + rave(sol_full t=1.1 w=0.2 d=2,4,6,8,10,12,14)" },
  { slug: "parallel-universe", name: "parallel-universe", mode: "branch", steps: 4, effects: "rave(vintage t=1.3 d=0,1,2,3) + rave(musicnet t=1.3 d=4,5,6,7) + rave(sol_ordinario t=1.3 d=8,9,10,11) + rave(percussion t=1.3 d=12,13,14,15)" },
  { slug: "space-sickness", name: "space-sickness", mode: "branch", steps: 3, effects: "dry(w=0.6) + rave(nasa t=1.4 n=0.2 w=0.25 rev) + rave(percussion w=0.15 q=0.6 d=8,9,10,11,12,13,14,15)" },
  { slug: "speaking-in-tongues", name: "speaking-in-tongues", mode: "branch", steps: 6, effects: "rave(VCTK t=1.8 n=0.4) + rave(VCTK t=2.0 n=0.5 d=0,1,2,3,4,5) + rave(VCTK t=1.5 n=0.6 d=8,9,10,11,12,13,14,15) + rave(isis t=1.7 n=0.3 shuf=8) + rave(isis t=2.2 n=0.35) + rave(sol_ordinario t=1.4 n=0.25 rev)" },
  { slug: "time-sick", name: "time-sick", mode: "sequential", steps: 2, effects: "rave(musicnet rev) -> rave(musicnet shuf=4 q=0.3)" },
] as const;

const slugSet = new Set(RECIPES.map((r) => r.slug));

/** Check whether a slug corresponds to a valid recipe. */
export function isValidRecipe(slug: string): boolean {
  return slugSet.has(slug);
}

/** Look up a recipe by slug, or undefined if not found. */
export function getRecipe(slug: string): Recipe | undefined {
  return RECIPES.find((r) => r.slug === slug);
}

/**
 * Format the full recipe list for Slack display, grouped by mode.
 */
export function formatRecipeList(): string {
  const sequential = RECIPES.filter((r) => r.mode === "sequential");
  const branch = RECIPES.filter((r) => r.mode === "branch");

  const fmt = (r: Recipe) => `\`${r.slug}\` \u2014 ${r.name} (${r.steps} steps)`;

  const sections: string[] = [];
  if (sequential.length > 0) {
    sections.push(`*Sequential (each step feeds the next):*\n${sequential.map(fmt).join("\n")}`);
  }
  if (branch.length > 0) {
    sections.push(`*Branch (all steps run in parallel, then mix):*\n${branch.map(fmt).join("\n")}`);
  }

  return `*Available Recipes (${RECIPES.length} total):*\n\n${sections.join("\n\n")}`;
}

/**
 * Find recipes whose slugs contain the given substring.
 * Returns up to 5 matches for "did you mean?" suggestions.
 */
export function suggestRecipes(input: string): Recipe[] {
  const lower = input.toLowerCase();
  return RECIPES.filter((r) => r.slug.includes(lower)).slice(0, 5);
}
