#!/usr/bin/env python3
"""Generate worker/src/recipes.ts from recipes/*.toml.

Reads all TOML recipe files and generates a TypeScript module that the
Cloudflare Worker uses for recipe validation, listing, and suggestion.

Usage:
    python scripts/generate_worker_recipes.py
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore[no-redef]


def find_repo_root() -> Path:
    """Find the repo root by looking for the recipes/ directory."""
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    if (repo_root / "recipes").is_dir():
        return repo_root
    if (Path.cwd() / "recipes").is_dir():
        return Path.cwd()
    return repo_root


def escape_ts_string(s: str) -> str:
    """Escape a string for use in a TypeScript double-quoted string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def annotate_step(step: dict) -> str:
    """Return an annotated label for a single recipe step."""
    effect = step.get("effect", "unknown")
    parts: list[str] = []
    if "model" in step:
        parts.append(step["model"])
    if "temperature" in step:
        parts.append(f"t={step['temperature']}")
    if "noise" in step:
        parts.append(f"n={step['noise']}")
    if "weight" in step:
        parts.append(f"w={step['weight']}")
    if step.get("reverse"):
        parts.append("rev")
    if "shuffle_chunks" in step:
        parts.append(f"shuf={step['shuffle_chunks']}")
    if "quantize" in step:
        parts.append(f"q={step['quantize']}")
    if "dims" in step:
        parts.append(f"d={step['dims']}")
    if "mix" in step:
        parts.append(f"mix={step['mix']}")
    if parts:
        return f"{effect}({' '.join(parts)})"
    return effect


def build_effects_chain(steps: list[dict], mode: str) -> str:
    """Build a human-readable effect chain string from recipe steps."""
    sep = " + " if mode == "branch" else " -> "
    return sep.join(annotate_step(s) for s in steps)


def load_recipes(recipes_dir: Path) -> list[dict]:
    """Load all TOML recipes and return sorted list of recipe metadata."""
    recipes = []
    for path in sorted(recipes_dir.glob("*.toml")):
        with open(path, "rb") as f:
            data = tomllib.load(f)
        meta = data.get("recipe", {})
        if not meta:
            continue
        slug = path.stem
        steps = data.get("steps", [])
        mode = meta.get("mode", "sequential")
        recipes.append({
            "slug": slug,
            "name": meta.get("name", slug),
            "mode": mode,
            "steps": len(steps),
            "effects": build_effects_chain(steps, mode),
        })
    return recipes


def generate_typescript(recipes: list[dict]) -> str:
    """Generate the TypeScript source for recipes.ts."""
    lines = [
        "/**",
        " * DO NOT EDIT -- this file is auto-generated by scripts/generate_worker_recipes.py",
        " * from recipes/*.toml. To update, run: python scripts/generate_worker_recipes.py",
        " */",
        "",
        "/** A rottengenizdat recipe definition. */",
        "export interface Recipe {",
        "  slug: string;",
        "  name: string;",
        '  mode: "sequential" | "branch";',
        "  steps: number;",
        "  effects: string;",
        "}",
        "",
        "/** All available recipes. */",
        "export const RECIPES: readonly Recipe[] = [",
    ]

    for r in recipes:
        slug = escape_ts_string(r["slug"])
        name = escape_ts_string(r["name"])
        mode = escape_ts_string(r["mode"])
        effects = escape_ts_string(r["effects"])
        lines.append(
            f'  {{ slug: "{slug}", name: "{name}", '
            f'mode: "{mode}", steps: {r["steps"]}, '
            f'effects: "{effects}" }},'
        )

    lines.append("] as const;")
    lines.append("")
    lines.append('const slugSet = new Set(RECIPES.map((r) => r.slug));')
    lines.append("")
    lines.append("/** Check whether a slug corresponds to a valid recipe. */")
    lines.append("export function isValidRecipe(slug: string): boolean {")
    lines.append("  return slugSet.has(slug);")
    lines.append("}")
    lines.append("")
    lines.append("/** Look up a recipe by slug, or undefined if not found. */")
    lines.append("export function getRecipe(slug: string): Recipe | undefined {")
    lines.append("  return RECIPES.find((r) => r.slug === slug);")
    lines.append("}")
    lines.append("")
    lines.append("/**")
    lines.append(" * Format the full recipe list for Slack display, grouped by mode.")
    lines.append(" */")
    lines.append("export function formatRecipeList(): string {")
    lines.append('  const sequential = RECIPES.filter((r) => r.mode === "sequential");')
    lines.append('  const branch = RECIPES.filter((r) => r.mode === "branch");')
    lines.append("")
    lines.append("  const fmt = (r: Recipe) => `\\`${r.slug}\\` \\u2014 ${r.name} (${r.steps} steps)`;")
    lines.append("")
    lines.append("  const sections: string[] = [];")
    lines.append("  if (sequential.length > 0) {")
    lines.append('    sections.push(`*Sequential (each step feeds the next):*\\n${sequential.map(fmt).join("\\n")}`);')
    lines.append("  }")
    lines.append("  if (branch.length > 0) {")
    lines.append('    sections.push(`*Branch (all steps run in parallel, then mix):*\\n${branch.map(fmt).join("\\n")}`);')
    lines.append("  }")
    lines.append("")
    lines.append('  return `*Available Recipes (${RECIPES.length} total):*\\n\\n${sections.join("\\n\\n")}`;')
    lines.append("}")
    lines.append("")
    lines.append("/**")
    lines.append(" * Find recipes whose slugs contain the given substring.")
    lines.append(' * Returns up to 5 matches for "did you mean?" suggestions.')
    lines.append(" */")
    lines.append("export function suggestRecipes(input: string): Recipe[] {")
    lines.append("  const lower = input.toLowerCase();")
    lines.append('  return RECIPES.filter((r) => r.slug.includes(lower)).slice(0, 5);')
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate worker/src/recipes.ts from TOML recipes")
    parser.add_argument("--recipes-dir", type=Path, default=None, help="Path to recipes directory")
    parser.add_argument("--output", type=Path, default=None, help="Output TypeScript file path")
    args = parser.parse_args()

    repo_root = find_repo_root()
    recipes_dir = args.recipes_dir or repo_root / "recipes"
    output_path = args.output or repo_root / "worker" / "src" / "recipes.ts"

    if not recipes_dir.is_dir():
        print(f"Error: recipes directory not found: {recipes_dir}", file=sys.stderr)
        sys.exit(1)

    recipes = load_recipes(recipes_dir)
    if not recipes:
        print("Error: no recipes found", file=sys.stderr)
        sys.exit(1)

    ts_source = generate_typescript(recipes)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(ts_source)

    print(f"Generated {output_path} with {len(recipes)} recipes")


if __name__ == "__main__":
    main()
